AllCops:
  TargetRubyVersion: 2.5.0
  Exclude:
    - bin/*
    - config/**/*
    - coverage/**/*
    - db/**/*
    - doc/**/*
    - log/**/*
    - public/**/*
    - script/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/models/*
    - spec/controllers/debts_controller_spec.rb
    - spec/controllers/users_controller_spec.rb
MethodCalledOnDoEndBlock:
  Enabled: true

Documentation:
  Exclude:
    - app/api/**/*
    - app/controllers/**/*
    - app/helpers/**/*

ClassAndModuleChildren:
  Enabled: false

Layout:
  Style/DotPosition:
    EnforcedStyle: trailing

Rails:
  Enabled: true