# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bailiff2_0_development

test:
  <<: *default
  database: bailiff2_0_test

production:
  <<: *default
  database: bailiff2_0_production
  username: bailiff2_0
  password: <%= ENV['BAILIFF2_0_DATABASE_PASSWORD'] %>
